### ISSUE TITLE
无法隐藏系统输入法

### ISSUE THREAD

**Issue by rcj60560** [StomHong/CustomizeKeyboard#10]
@StomHong 
@xiwenhec @ziyeyouhu 
demo中第二个edittext选中时，按菜单切到后台之后，在选中项目切回来，系统自带输入法会一直弹出来 没办法隐藏
 keyboardUtil.hideAllKeyBoard(); 我在onresume里调用 没效果

**Comment by StomHong** [comment]
这个问题可以在AndroidManifest.xml里面配置android:windowSoftInputMode="stateAlwaysHidden"
