### ISSUE TITLE
在界面点击back后isSuper没有复位

### ISSUE THREAD

**Issue by ReadTheFuckingCode** [StomHong/CustomizeKeyboard#14]
可能导致大小切换错乱

**Comment by ReadTheFuckingCode** [comment]
顺便说一下当键盘弹出并且界面生命周期走了onPause后：1键盘的shift容易出问题
                                                                                              2系统键盘会把安全键盘顶上去

**Comment by StomHong** [comment]
反馈的问题确实存在，会尽快修复。2系统键盘会把安全键盘顶上去？没测出来。

**Comment by ReadTheFuckingCode** [comment]
复现的话就是安全键盘弹出后切换应用，然后再切回来。这时候系统键盘就会在安全键盘下面

**Comment by ReadTheFuckingCode** [comment]
> 系统键盘会把安全键盘顶上去？没测出

复现的话就是安全键盘弹出后切换应用，然后再切回来。这时候系统键盘就会在安全键盘下面
