### ISSUE TITLE
关于系统键盘出现在安全键盘下方的描述

### ISSUE THREAD

**Issue by ReadTheFuckingCode** [StomHong/CustomizeKeyboard#15]
应用切换时复现

![Screenshot_20210328_103235_com example myapplication 1](https://user-images.githubusercontent.com/42809048/112740694-abd86100-8fb1-11eb-8861-13607bbb1af3.jpg)
![Screenshot_20210328_103248_com huawei android launcher 1](https://user-images.githubusercontent.com/42809048/112740698-bbf04080-8fb1-11eb-8cf1-e8a6f94e818f.jpg)
![Screenshot_20210328_103253_com example myapplication 1](https://user-images.githubusercontent.com/42809048/112740700-c579a880-8fb1-11eb-94fc-bd3a687a9f71.jpg)

**Comment by StomHong** [comment]
1.0.2版本没有出现这个问题，你试一下？

**Comment by ReadTheFuckingCode** [comment]
> 1.0.2版本没有出现这个问题，你试一下？

更新到1.0.2了，这个应该和系统键盘弹出的机制有关系，
我用的华为手机，安卓10，specialEd.setShowSoftInputOnFocus(false)设置了之后依然会弹出，
正在分析原因

**Comment by StomHong** [comment]
在AndroidManifest.xml里面配置android:windowSoftInputMode="stateAlwaysHidden"

**Comment by ReadTheFuckingCode** [comment]
> 在AndroidManifest.xml里面配置android:windowSoftInputMode="stateAlwaysHidden"

确实，落下了这里，不好意思。那我把这个关了把，大佬，我想学习下系统键盘是怎么被唤醒的。
windowSoftInputMode这个如果不设置的话就会出现上面的问题，但是我不知道为什么会出现这种状况。
大佬可否指点以下

**Comment by StomHong** [comment]
google一下
