### ISSUE TITLE
为什么布局中要在最外层嵌套个ScrollView? 

### ISSUE THREAD

**Issue by Code6666** [StomHong/CustomizeKeyboard#3]
而且高度还得设置为0，权重为1 ？  这样很有局限性

**Comment by rcj60560** [comment]
@StomHong @Code6666 同问 为什么要添加一个scrollview呢 不太明白

**Comment by trista315049** [comment]
scrollview 不添加的话怎么处理？

**Comment by RealMoMo** [comment]
同问

**Comment by StomHong** [comment]
能不能把你们的使用场景具体描述一下，有什么样的局限性，这样我才能确定要不要改写以及如何改写

**Comment by StomHong** [comment]
已改写，不再需要ScrollView
