### ISSUE TITLE
华为底部的虚拟键盘，遮挡住了自定义键盘底部，怎么解决哈

### ISSUE THREAD

**Issue by boyrt** [StomHong/CustomizeKeyboard#6]
华为底部的虚拟键盘，遮挡住了自定义键盘底部，怎么解决哈

**Comment by boyrt** [comment]
已解决。发现是自己布局没写好。scrollview没设置成 weight的形式

**Comment by rcj60560** [comment]
@boyrt 我也是有一台手机 底部有虚拟键盘  弹出数字键盘的时候被遮挡住了一部分 请问你是怎么处理的
