### ISSUE TITLE
物理返回键能否判断下 自定义键盘是否弹出

### ISSUE THREAD

**Issue by boyrt** [StomHong/CustomizeKeyboard#7]
物理返回键能否判断下 自定义键盘是否弹出。如果弹出的话，物理返回键关闭自定义键盘，而不是直接返回上一个界面或退出app。
KeyboardUtil是否能提供个api，用于判断键盘是否显示。

**Comment by StomHong** [comment]
我在手机小米手机上测试，没有出现你说的情况

**Comment by StomHong** [comment]
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK && event.getRepeatCount() == 0 ) {
            if(keyboardUtil.isShow){
                keyboardUtil.hideSystemKeyBoard();
                keyboardUtil.hideAllKeyBoard();
                keyboardUtil.hideKeyboardLayout();
            }else {
                return super.onKeyDown(keyCode, event);
            }

            return false;
        } else
            return super.onKeyDown(keyCode, event);
    }
